services:
  - type: web
    name: restaurapp-backend
    plan: free
    runtime: java
    buildCommand: ./gradlew clean bootJar
    startCommand: java -jar build/libs/restaurapp.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
